// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbuLljE5_K34XOu1RXvWuaWrH515-BJw',
    appId: '1:904040468234:web:5c1ceb45c61b838496b4f3',
    messagingSenderId: '904040468234',
    projectId: 'shopquanao-69955',
    authDomain: 'shopquanao-69955.firebaseapp.com',
    databaseURL: 'https://shopquanao-69955-default-rtdb.firebaseio.com',
    storageBucket: 'shopquanao-69955.firebasestorage.app',
    measurementId: 'G-S4QYENJDS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb8RoBdsg67FzPu2NAx52K6w9rGO6oi_U',
    appId: '1:904040468234:android:2dcee173a561386696b4f3',
    messagingSenderId: '904040468234',
    projectId: 'shopquanao-69955',
    databaseURL: 'https://shopquanao-69955-default-rtdb.firebaseio.com',
    storageBucket: 'shopquanao-69955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2Ged9eYi5vwZbdbrcPV9-rlzheniJvc',
    appId: '1:904040468234:ios:24183a9f05f904ba96b4f3',
    messagingSenderId: '904040468234',
    projectId: 'shopquanao-69955',
    databaseURL: 'https://shopquanao-69955-default-rtdb.firebaseio.com',
    storageBucket: 'shopquanao-69955.firebasestorage.app',
    iosBundleId: 'com.example.nhom4Muasamthoitrangonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs2Ged9eYi5vwZbdbrcPV9-rlzheniJvc',
    appId: '1:904040468234:ios:24183a9f05f904ba96b4f3',
    messagingSenderId: '904040468234',
    projectId: 'shopquanao-69955',
    databaseURL: 'https://shopquanao-69955-default-rtdb.firebaseio.com',
    storageBucket: 'shopquanao-69955.firebasestorage.app',
    iosBundleId: 'com.example.nhom4Muasamthoitrangonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvbuLljE5_K34XOu1RXvWuaWrH515-BJw',
    appId: '1:904040468234:web:ff75e2c109cd3cf696b4f3',
    messagingSenderId: '904040468234',
    projectId: 'shopquanao-69955',
    authDomain: 'shopquanao-69955.firebaseapp.com',
    databaseURL: 'https://shopquanao-69955-default-rtdb.firebaseio.com',
    storageBucket: 'shopquanao-69955.firebasestorage.app',
    measurementId: 'G-WFT1GB4R3T',
  );

}